An error occurred while executing the following cell:
------------------
# Imports
from tensorflow.python.client import device_lib
from psutil import virtual_memory
import cv2
from google.colab.patches import cv2_imshow

%tensorflow_version 2.x
import tensorflow as tf
import os


from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score


from sklearn.datasets.samples_generator import make_blobs
from IPython import display
from matplotlib import pyplot as plt

import numpy as np

import pathlib
import shutil
import tempfile

from tqdm import tqdm
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4648/1226003757.py in <module>
      2 from tensorflow.python.client import device_lib
      3 from psutil import virtual_memory
----> 4 import cv2
      5 from google.colab.patches import cv2_imshow
      6 

ModuleNotFoundError: No module named 'cv2'
ModuleNotFoundError: No module named 'cv2'
