An error occurred while executing the following cell:
------------------
import os
import pandas as pd
from collections import OrderedDict
import matplotlib.pyplot as plt
import numpy as np

try:
    import torch
except ModuleNotFoundError:
    %pip install -qq torch
    import torch
import torch.nn as nn
import torch.nn.functional as F

try:
    import torchvision
except ModuleNotFoundError:
    %pip install -qq torchvision
    import torchvision
import torchvision.transforms as transforms

try:
    from pytorch_lightning import LightningDataModule, LightningModule, Trainer
except ModuleNotFoundError:
    %pip install -qq pytorch_lightning
    from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from torch.utils.data import DataLoader, random_split

try:
    from vae_celeba_lightning import VAE
except ModuleNotFoundError:
    %pip install -qq vae_celeba_lightning
    from vae_celeba_lightning import VAE
try:
    from einops import rearrange
except ModuleNotFoundError:
    %pip install -qq einops
    from einops import rearrange
from torchvision.utils import make_grid

try:
    from tqdm import tqdm
except ModuleNotFoundError:
    %pip install -qq tqdm
    from tqdm import tqdm
try:
    from lvm_plots_utils import get_random_samples, get_grid_samples, plot_scatter_plot, get_imrange, make_imrange
except ModuleNotFoundError:
    %pip install -qq lvm_plots_utils
    from lvm_plots_utils import get_random_samples, get_grid_samples, plot_scatter_plot, get_imrange, make_imrange
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4678/2329549897.py in <module>
     29 try:
---> 30     from vae_celeba_lightning import VAE
     31 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'vae_celeba_lightning'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4678/2329549897.py in <module>
     31 except ModuleNotFoundError:
     32     get_ipython().run_line_magic('pip', 'install -qq vae_celeba_lightning')
---> 33     from vae_celeba_lightning import VAE
     34 try:
     35     from einops import rearrange

ModuleNotFoundError: No module named 'vae_celeba_lightning'
ModuleNotFoundError: No module named 'vae_celeba_lightning'
